/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Acceso;
import Modelo.Neumatico;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class AltaNeu extends javax.swing.JDialog {

    //Atributos clase neumático
    private int cod;
    private String codTemp;
    private String brand;
    private String model;
    private int width;
    private String widthTemp;
    private String profile;
    private double diameter;
    private String diameterTemp;
    private int ic;
    private String iv;
    private double price;
    private String priceTemp;

    //Objeto para acceder a la base de datos
    private Acceso con;

    /**
     * Creates new form AltaNeu
     */
    public AltaNeu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //Inicializamos el objeto de acceso a la base de datos
        con = new Acceso();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFCodNeu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFBrandNeu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFModelNeu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFWidthNeu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jCBProfileNeu = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jTFDiameterNeu = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jCBICNeu = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jCBIVNeu = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jTFPriceNeu = new javax.swing.JTextField();
        jBSaveNeu = new javax.swing.JButton();
        jBCancelNeu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("NUEVO NEUMÁTICO");

        jLabel2.setText("Código:");

        jTFCodNeu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFCodNeuKeyTyped(evt);
            }
        });

        jLabel3.setText("Marca:");

        jTFBrandNeu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFBrandNeuKeyTyped(evt);
            }
        });

        jLabel4.setText("Modelo:");

        jLabel5.setText("Ancho:");

        jTFWidthNeu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFWidthNeuKeyTyped(evt);
            }
        });

        jLabel6.setText("Perfil:");

        jCBProfileNeu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCBProfileNeu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BAJO", "MEDIO", "ALTO" }));

        jLabel7.setText("Diámetro:");

        jTFDiameterNeu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFDiameterNeuKeyTyped(evt);
            }
        });

        jLabel8.setText("IC:");

        jCBICNeu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCBICNeu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "70", "80", "90", "100", "110", "120" }));

        jLabel9.setText("IV:");

        jCBIVNeu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCBIVNeu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "H", "N", "Q", "R", "S", "T", "V", "W", "Y" }));

        jLabel10.setText("Precio:");

        jTFPriceNeu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFPriceNeuKeyTyped(evt);
            }
        });

        jBSaveNeu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBSaveNeu.setForeground(new java.awt.Color(0, 102, 0));
        jBSaveNeu.setText("GUARDAR");
        jBSaveNeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSaveNeuActionPerformed(evt);
            }
        });

        jBCancelNeu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBCancelNeu.setForeground(new java.awt.Color(204, 0, 0));
        jBCancelNeu.setText("CANCELAR");
        jBCancelNeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelNeuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jBSaveNeu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(jBCancelNeu)
                .addGap(145, 145, 145))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTFBrandNeu, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(jTFCodNeu)
                            .addComponent(jTFModelNeu, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFWidthNeu, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBProfileNeu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jTFDiameterNeu, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jCBICNeu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jCBIVNeu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTFPriceNeu, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTFDiameterNeu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(jTFCodNeu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jTFBrandNeu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addComponent(jTFModelNeu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jCBICNeu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jTFWidthNeu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jCBIVNeu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jCBProfileNeu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTFPriceNeu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSaveNeu)
                    .addComponent(jBCancelNeu))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSaveNeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSaveNeuActionPerformed

        codTemp = jTFCodNeu.getText().trim();
        try {
            cod = Integer.parseInt(codTemp);
        } catch (NumberFormatException e) {
            //Encapsulamos el parseo para que no pete
            //Si meten letras, dado que lo igualamos a 0
            cod = 0;
        }
        brand = jTFBrandNeu.getText().trim();
        model = jTFModelNeu.getText().trim();

        widthTemp = jTFWidthNeu.getText().trim();
        try {
            width = Integer.parseInt(widthTemp);
        } catch (NumberFormatException e) {
            //Encapsulamos el parseo para que no pete
            //Si meten letras, dado que lo igualamos a 0
            width = 0;
        }
        profile = jCBProfileNeu.getSelectedItem().toString();

        diameterTemp = jTFDiameterNeu.getText().trim();
        try {
            diameter = Double.parseDouble(diameterTemp);
        } catch (NumberFormatException e) {
            //Encapsulamos el parseo para que no pete
            //Si meten letras, dado que lo igualamos a 0
            diameter = 0;
        }

        ic = Integer.parseInt(jCBICNeu.getSelectedItem().toString());
        iv = jCBIVNeu.getSelectedItem().toString();

        priceTemp = jTFPriceNeu.getText().trim();
        try {
            price = Double.parseDouble(priceTemp);
        } catch (NumberFormatException e) {
            //Encapsulamos el parseo para que no pete
            //Si meten letras, dado que lo igualamos a 0
            price = 0;
        }

        //Varible para guardar confirmación usuario
        int confirm;

        if (!(cod == 0) && !con.verifyNeuCod(cod) && !brand.isEmpty() && !model.isEmpty()
                && !(width == 0) && !profile.isEmpty() && !(diameter == 0)
                && !(ic == 0) && !iv.isEmpty() && !(price == 0)) {
            //Verificamos que ningún campo esté vació o que el código del neumático esté disponible
            confirm = JOptionPane.showConfirmDialog(this, "¿Quiere guardar los datos introducidos?", "Confirmar datos", JOptionPane.OK_CANCEL_OPTION);
            //Si acepta
            if (confirm == JOptionPane.OK_OPTION) {
                //Guardamos los datos en un objeto neumatico
                Neumatico neu = new Neumatico(cod, brand, model, width, profile, diameter, ic, iv, price);

                //Lo escribimos
                con.saveNeu(neu);

                //Vaciamos los campos
                jTFCodNeu.setText("");
                jTFBrandNeu.setText("");
                jTFModelNeu.setText("");
                jTFWidthNeu.setText("");
                jCBProfileNeu.setSelectedIndex(0);
                jTFDiameterNeu.setText("");
                jCBICNeu.setSelectedIndex(0);
                jCBIVNeu.setSelectedIndex(0);
                jTFPriceNeu.setText("");

            }
        } else if (con.verifyNeuCod(cod)) {
            JOptionPane.showMessageDialog(this, "CÓDIGO NO DISPONIBLE. \nYa existe un neumático con ese código en nuestra Base de Datos.");
        } else {
            JOptionPane.showMessageDialog(this, "Debe introducir todos los datos del neumático para guardarlo. Para salir sin guardar pulse CANCELAR.");
        }

    }//GEN-LAST:event_jBSaveNeuActionPerformed

    private void jBCancelNeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelNeuActionPerformed
        //Comprobamos si el usaurio ha introducido algún dato en los campos de texto
        if (!jTFCodNeu.getText().isEmpty() || !jTFBrandNeu.getText().isEmpty() || !jTFModelNeu.getText().isEmpty()
                || !jTFWidthNeu.getText().isEmpty() || !jTFDiameterNeu.getText().isEmpty() || !jTFPriceNeu.getText().isEmpty()) {
            int confirm = JOptionPane.showConfirmDialog(this, "Los datos introducidos se borrarán. ¿Desea salir sin guardar?", "Cierre de Alta de Neumáticos", JOptionPane.OK_CANCEL_OPTION);
            //Si acepta
            if (confirm == JOptionPane.OK_OPTION) {
                // Cerramos la ventana
                dispose();
            }

        } else {
            //En caso contrario cerramos directamente la ventana
            dispose();
        }


    }//GEN-LAST:event_jBCancelNeuActionPerformed

    private void jTFCodNeuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCodNeuKeyTyped
        // Limitar caracteres numéricos de entrada
        String codNeuString = jTFCodNeu.getText().trim();
        for (int i = 0; i < codNeuString.length(); i++) {
            if (Character.isLetter(codNeuString.charAt(i))) {
                //Si es letra avisa y no deja escribir
                getToolkit().beep();
                evt.consume();
                JOptionPane.showMessageDialog(null, "Código de neumático incorrecto. Solamente se aceptan números enteros.");
                //Vaciamos el campo dado que es erróneo
                jTFCodNeu.setText("");
            }
        }
    }//GEN-LAST:event_jTFCodNeuKeyTyped

    private void jTFBrandNeuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFBrandNeuKeyTyped
        // Limitar caracteres alfabéticos de entrada
        String brandNeuString = jTFBrandNeu.getText().trim();
        for (int i = 0; i < brandNeuString.length(); i++) {
            if (Character.isDigit(brandNeuString.charAt(i))) {
                //Si es un valor dígito avisa y no deja escribir
                getToolkit().beep();
                evt.consume();
                JOptionPane.showMessageDialog(null, "Marca incorrecta. Solamente se aceptan valores alfabéticos.");
                //Vaciamos el campo dado que es erróneo
                jTFBrandNeu.setText("");
            }
        }
    }//GEN-LAST:event_jTFBrandNeuKeyTyped

    private void jTFWidthNeuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFWidthNeuKeyTyped
        // Limitar caracteres numéricos de entrada
        String widthNeuString = jTFWidthNeu.getText().trim();
        for (int i = 0; i < widthNeuString.length(); i++) {
            if (Character.isLetter(widthNeuString.charAt(i))) {
                //Si es letra avisa y no deja escribir
                getToolkit().beep();
                evt.consume();
                JOptionPane.showMessageDialog(null, "Ancho incorrecto. Solamente se aceptan números enteros.");
                //Vaciamos el campo dado que es erróneo
                jTFWidthNeu.setText("");
            }
        }
    }//GEN-LAST:event_jTFWidthNeuKeyTyped

    private void jTFDiameterNeuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFDiameterNeuKeyTyped
        // Limitar caracteres numéricos de entrada
        String diameterNeuString = jTFDiameterNeu.getText().trim();
        for (int i = 0; i < diameterNeuString.length(); i++) {
            if (Character.isLetter(diameterNeuString.charAt(i))) {
                //Si es letra avisa y no deja escribir
                getToolkit().beep();
                evt.consume();
                JOptionPane.showMessageDialog(null, "Diámetro incorrecto. Solamente se aceptan valores numéricos.");
                //Vaciamos el campo dado que es erróneo
                jTFDiameterNeu.setText("");
            }
        }
    }//GEN-LAST:event_jTFDiameterNeuKeyTyped

    private void jTFPriceNeuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFPriceNeuKeyTyped
        // Limitar caracteres numéricos de entrada
        String priceNeuString = jTFPriceNeu.getText().trim();
        for (int i = 0; i < priceNeuString.length(); i++) {
            if (Character.isLetter(priceNeuString.charAt(i))) {
                //Si es letra avisa y no deja escribir
                getToolkit().beep();
                evt.consume();
                JOptionPane.showMessageDialog(null, "Precio incorrecto. Solamente se aceptan valores numéricos.");
                //Vaciamos el campo dado que es erróneo
                jTFPriceNeu.setText("");
            }
        }
    }//GEN-LAST:event_jTFPriceNeuKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaNeu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaNeu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaNeu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaNeu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AltaNeu dialog = new AltaNeu(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelNeu;
    private javax.swing.JButton jBSaveNeu;
    private javax.swing.JComboBox<String> jCBICNeu;
    private javax.swing.JComboBox<String> jCBIVNeu;
    private javax.swing.JComboBox<String> jCBProfileNeu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTFBrandNeu;
    private javax.swing.JTextField jTFCodNeu;
    private javax.swing.JTextField jTFDiameterNeu;
    private javax.swing.JTextField jTFModelNeu;
    private javax.swing.JTextField jTFPriceNeu;
    private javax.swing.JTextField jTFWidthNeu;
    // End of variables declaration//GEN-END:variables
}
