/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Acceso;
import javax.swing.JOptionPane;
//Librerías para icono
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Usuario
 */
public class Menu extends javax.swing.JFrame {

    //Objeto para acceder a la base de datos
    private Acceso con;
    private static final String TABLA_NEUMATICOS = "neumatico";
    private static final String TABLA_FACTURAS = "factura";

//    //Nuestro icono
//    Icon img;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
//        //Forma 1
//        img = new ImageIcon(getClass().getResource("../img/tire_on_fire.jpg"));
//        //Forma 2
//        ImagePanel panel = new ImagePanel(new ImageIcon("../img/tire_on_fire.jpg").getImage());
//        JFrame frame = new JFrame();
//        frame.getContentPane().add(panel);
//        frame.pack();
//        frame.setVisible(true);
        //Inicializamos el objeto
        con = new Acceso();
        //Abrimos conexión a la base de datos
        con.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMINewNeu = new javax.swing.JMenuItem();
        jMIListNeu = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMINewInv = new javax.swing.JMenuItem();
        jMIPrintInv = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tire_on_fire.png"))); // NOI18N

        jMenu1.setText("Neumáticos    ");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMINewNeu.setText("Alta Neumático");
        jMINewNeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMINewNeuActionPerformed(evt);
            }
        });
        jMenu1.add(jMINewNeu);

        jMIListNeu.setText("Listado Neumáticos");
        jMIListNeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIListNeuActionPerformed(evt);
            }
        });
        jMenu1.add(jMIListNeu);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Facturación    ");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMINewInv.setText("Nueva Factura");
        jMINewInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMINewInvActionPerformed(evt);
            }
        });
        jMenu3.add(jMINewInv);

        jMIPrintInv.setText("Imprimir Factura");
        jMIPrintInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIPrintInvActionPerformed(evt);
            }
        });
        jMenu3.add(jMIPrintInv);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel1)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMIListNeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIListNeuActionPerformed

        if (con.verifyNumberOfRows(TABLA_NEUMATICOS) != 0) {
            new ListNeu(this, true).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "No existen neumáticos en la base de datos. \n¡De de alta su primer neumático!");
        }
    }//GEN-LAST:event_jMIListNeuActionPerformed

    private void jMINewNeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMINewNeuActionPerformed
        AltaNeu an = new AltaNeu(this, true);
        an.setVisible(true);
    }//GEN-LAST:event_jMINewNeuActionPerformed

    private void jMINewInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMINewInvActionPerformed
        AltaFac af = new AltaFac(this, true);
        af.setVisible(true);
    }//GEN-LAST:event_jMINewInvActionPerformed

    private void jMIPrintInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIPrintInvActionPerformed
        if (con.verifyNumberOfRows(TABLA_FACTURAS) != 0) {
            new PrintFac(this, true).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "No existen facturas en la base de datos. \n¡Realice su primera factura! \nFacturación > Nueva factura");
        }
    }//GEN-LAST:event_jMIPrintInvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMIListNeu;
    private javax.swing.JMenuItem jMINewInv;
    private javax.swing.JMenuItem jMINewNeu;
    private javax.swing.JMenuItem jMIPrintInv;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
