/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Acceso;
import Modelo.Factura;
import Modelo.LineaFactura;
import com.itextpdf.io.image.ImageDataFactory;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.border.Border;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.IElement;
import com.itextpdf.layout.element.Image;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.property.TextAlignment;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class PrintFac extends javax.swing.JDialog {

    //Recursos para facturas
    private final String path;
    private final String imgPath;

    //Objeto de acceso a la base de datos
    private Acceso con;

    //Modelo para la JTable
    private DefaultTableModel model;

    //Listados sacados de la base de datos
    private List<Factura> invoicesList;
    private List<LineaFactura> linesList;

    //Objeto factura seleccionado
    private Factura invoice;

    /**
     * Creates new form PrintFac
     */
    public PrintFac(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        path = "./src/Outputs/";
        imgPath = "/img/tire_on_fire.png";
        initComponents();
        //Inicializamos el controlador
        con = new Acceso();
        //Inicializamos la lista donde meteremos las facturas que leamos de la base de datos
        invoicesList = new ArrayList<>();

        //Sacamos los datos e inicializamos la tabla con los datos de la base de datos
        initTable();

        //El botón de imprimir aparecerá deshabilitado
        jBPrint.setEnabled(false);//Lo habilitaremos cuando se selecione una fila de la tabla
    }

    public void initTable() {
        //Inicializamos modelo
        model = new DefaultTableModel();
        //Nombramos las columnas
        String[] columnNames = {"Nº Factura", "Fecha", "NIF Cliente", "NIF Emisor", "Subtotal", "IVA", "Total"};
        model.setColumnIdentifiers(columnNames);
        model.setRowCount(0);

        //Accedemos a los datos
        invoicesList = con.readTableInv();
        if (invoicesList.size() != 0) {
            for (Factura inv : invoicesList) {
                Object[] rowData = new Object[columnNames.length];
                rowData[0] = inv.getNumFactura();
                rowData[1] = inv.getCurrentDate();
                rowData[2] = inv.getNifClient();
                rowData[3] = inv.getNifCompany();
                rowData[4] = inv.getBase();
                rowData[5] = inv.getTaxAmount();
                rowData[6] = inv.getTotal();
                model.addRow(rowData);
            }
        }

        this.jTInvList.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTFPrintNumInv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFPrintNIFClient = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTFPrintDate = new javax.swing.JTextField();
        jTFPrintCompanyName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTFPrintBaseInv = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTFPrintTax = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTFPrintTotalInv = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTFPrintNumAcc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTInvList = new javax.swing.JTable();
        jBPrint = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jBClosePrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("IMPRIMIR FACTURAS");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FACTURAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel2.setText("Num-Factura:");

        jTFPrintNumInv.setEditable(false);

        jLabel3.setText("NIF-Cliente:");

        jTFPrintNIFClient.setEditable(false);

        jLabel4.setText("Fecha:");

        jLabel5.setText("NIF-Emisor:");

        jTFPrintDate.setEditable(false);

        jTFPrintCompanyName.setEditable(false);

        jLabel6.setText("Subtotal:");

        jTFPrintBaseInv.setEditable(false);

        jLabel7.setText("IVA 21%:");

        jTFPrintTax.setEditable(false);

        jLabel8.setText("Total Factura:");

        jTFPrintTotalInv.setEditable(false);

        jLabel9.setText("Num-Cuenta:");

        jTFPrintNumAcc.setEditable(false);

        jTInvList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nº Factura", "Fecha", "NIF Cliente", "NIF Emisor", "Subtotal", "IVA", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTInvList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTInvListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTInvList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTFPrintNumInv, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(jTFPrintNIFClient)
                                    .addComponent(jTFPrintBaseInv)
                                    .addComponent(jTFPrintTax)
                                    .addComponent(jTFPrintTotalInv))
                                .addGap(61, 61, 61)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTFPrintDate, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(jTFPrintCompanyName)))
                            .addComponent(jTFPrintNumAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFPrintNumInv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTFPrintDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTFPrintNIFClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jTFPrintCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTFPrintBaseInv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTFPrintTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTFPrintTotalInv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTFPrintNumAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBPrint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBPrint.setForeground(new java.awt.Color(0, 102, 0));
        jBPrint.setText("IMPRIMIR");
        jBPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPrintActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/happy_printer.png"))); // NOI18N

        jBClosePrint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBClosePrint.setForeground(new java.awt.Color(153, 0, 0));
        jBClosePrint.setText("CERRAR");
        jBClosePrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBClosePrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jBPrint)
                                        .addGap(38, 38, 38))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBClosePrint)
                                .addGap(46, 46, 46)))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jBPrint)
                        .addGap(101, 101, 101)
                        .addComponent(jBClosePrint)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTInvListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTInvListMouseClicked
        // Cuando el usuario hace click en la tabla cogemos el número de fila
        int row = jTInvList.rowAtPoint(evt.getPoint());
        //Creamos el objeto factura para guardar los datos de la selección
        invoice = invoicesList.get(row);
        
        //Seteamos los campos
        jTFPrintBaseInv.setText(jTInvList.getValueAt(row, 4).toString());
        jTFPrintCompanyName.setText(jTInvList.getValueAt(row, 3).toString());
        jTFPrintDate.setText(jTInvList.getValueAt(row, 1).toString());
        jTFPrintNIFClient.setText(jTInvList.getValueAt(row, 2).toString());
        jTFPrintNumAcc.setText(invoice.getBankAccount());
        jTFPrintNumInv.setText(jTInvList.getValueAt(row, 0).toString());
        jTFPrintTax.setText(jTInvList.getValueAt(row, 5).toString());
        jTFPrintTotalInv.setText(jTInvList.getValueAt(row, 6).toString());
        
        //Habilitamos el botón de impresión
        jBPrint.setEnabled(true);
    }//GEN-LAST:event_jTInvListMouseClicked

    private void jBClosePrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBClosePrintActionPerformed
        //Cerramos la ventana
        dispose();
    }//GEN-LAST:event_jBClosePrintActionPerformed

    private void jBPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPrintActionPerformed
        // Imprimimos una factura
        printPDF();

    }//GEN-LAST:event_jBPrintActionPerformed

    private void printPDF() {
        String invoceName = "factura_A0" + invoice.getNumFactura() + "-" + invoice.getCurrentDate().substring(6) + "_" + invoice.getNifClient() + "_" 
                + invoice.getCurrentDate().substring(0, 2) + invoice.getCurrentDate().substring(3, 5) + invoice.getCurrentDate().substring(6) + ".pdf";
        try {
            PdfDocument pdf = new PdfDocument(new PdfWriter(path + invoceName));
            Document doc = new Document(pdf);

            //Agrega rótulo
            Table header = new Table(new float[]{1});
            header.setWidthPercent(100);
            header.addCell("FACTURA").setBold().setTextAlignment(TextAlignment.CENTER);
            doc.add(header);
            //Añadimos salto de línea
            doc.add(new Paragraph("\n"));

            //Agrega imagen
            Image img = new Image(ImageDataFactory.create(getClass().getResource(imgPath)));
            img.setHeight(100);
            img.setWidth(200);
            doc.add(img);
            //Añadimos salto de línea
            doc.add(new Paragraph("\n"));

            //Primera línea y siguientes
            doc.add(new Paragraph("Información del cliente").setBold());
            doc.add(new Paragraph("Nº FACTURA: " + "A0" + invoice.getNumFactura() + "-" + invoice.getCurrentDate().substring(6)));
            doc.add(new Paragraph("Fecha: " + invoice.getCurrentDate()));
            doc.add(new Paragraph("NIF Cliente: " + invoice.getNifClient()));
            //Datos de la compañía
            doc.add(new Paragraph("NEUMÁTICOS NEUFASHION").setBold().setTextAlignment(TextAlignment.RIGHT));
            doc.add(new Paragraph("Calle locomotor 40").setTextAlignment(TextAlignment.RIGHT));
            doc.add(new Paragraph("14089 Córdoba").setTextAlignment(TextAlignment.RIGHT));
            doc.add(new Paragraph(invoice.getNifCompany()).setTextAlignment(TextAlignment.RIGHT));
            //Añadimos salto de línea
            doc.add(new Paragraph("\n"));

            //Contruimos la tabla de datos
            Table data = new Table(new float[]{2, 2, 2});
            data.setWidthPercent(100);
            //Cabeceras
            data.addHeaderCell(new Cell().add("Unidades"));
            data.addHeaderCell(new Cell().add("Concepto"));
            data.addHeaderCell(new Cell().add("Precio"));

            //Sacamos los datos de las líneas de factura
            linesList = con.readTableInvLine(invoice.getNumFactura());

            for (LineaFactura line : linesList) {
                data.addCell( new Cell().add(String.valueOf(line.getNumNeu())));
                data.addCell(new Cell().add(line.getConcept()));
                data.addCell(new Cell().add(String.valueOf(line.getPrice())));
            }

            doc.add(data);
            //Añadimos salto de línea
            doc.add(new Paragraph("\n"));

            //Añadimos los totales
            Table invoiceTotals = new Table(new float[]{2, 2});
            invoiceTotals.setWidthPercent(45);
            invoiceTotals.setMarginLeft(200);
            invoiceTotals.addCell(new Cell().add("Base imponible: ")).setTextAlignment(TextAlignment.LEFT);
            invoiceTotals.addCell(new Cell().add(String.valueOf(invoice.getBase())));
            invoiceTotals.addCell(new Cell().add("IVA: ")).setTextAlignment(TextAlignment.LEFT);
            invoiceTotals.addCell(new Cell().add(String.valueOf(invoice.getTaxAmount())));
            invoiceTotals.addCell(new Cell().add("Total Factura: ")).setTextAlignment(TextAlignment.LEFT).setBold();
            invoiceTotals.addCell(new Cell().add(String.valueOf(invoice.getTotal()))).setBold();
            //Recorremos la tabla para quitarle los bordes a las celdas
            for (IElement iElement : invoiceTotals.getChildren()) {
                ((Cell) iElement).setBorder(Border.NO_BORDER);
            }
            //Añadimos la tabla con los totales de la factura al documento
            doc.add(invoiceTotals);
            //Añadimos salto de línea
            doc.add(new Paragraph("\n\n\n"));

            //Añadimos el número de cuenta
            doc.add(new Paragraph("Forma de pago: Transferencia\nNº Cuenta: " + invoice.getBankAccount()).setBold());
            
            doc.close();

            JOptionPane.showMessageDialog(null, "Se ha creado el fichero " + invoceName + " con la factura correspondiente");

        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintFac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintFac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintFac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintFac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PrintFac dialog = new PrintFac(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBClosePrint;
    private javax.swing.JButton jBPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFPrintBaseInv;
    private javax.swing.JTextField jTFPrintCompanyName;
    private javax.swing.JTextField jTFPrintDate;
    private javax.swing.JTextField jTFPrintNIFClient;
    private javax.swing.JTextField jTFPrintNumAcc;
    private javax.swing.JTextField jTFPrintNumInv;
    private javax.swing.JTextField jTFPrintTax;
    private javax.swing.JTextField jTFPrintTotalInv;
    private javax.swing.JTable jTInvList;
    // End of variables declaration//GEN-END:variables
}
